### ISSUE TITLE
[열차변경] 에코레일, 국악와인 소화물차 스프라이트 개선

### ISSUE THREAD

**Issue by EightonEight** [OpenCreative/KR_Plus_Set#64]
#### ==========[필수스프라이트]==========
![Luggage_Car](https://user-images.githubusercontent.com/77984422/217947234-a2cbfb5b-bc82-4d51-a050-81046e72e3f6.png)
`Luggage_Car`

#### ==========[설명]==========
에코레일, 국악와인열차의 소화물차 스프라이트를 실제(고속소화물차 기반, [KoreanGRF/KoreanTrainSet#389](https://github.com/KoreanGRF/KoreanTrainSet/issues/389))에 맞게 수정하였습니다.

에코레일의 경우 차량을 뒤집으면 도색이 자연스럽게 이어질 수 있도록 하였습니다.

**References:**
* <https://youtu.be/PyZCHNLKbO4>
* <https://youtu.be/bxI1X59iNu8?t=50>
* <https://youtu.be/wOCoOZCmb2M?t=85>
* <https://youtu.be/9Qva1KIXCsw?t=50>
* <https://blog.naver.com/tntjrlwl/222724054620>

#### ==========[KTS+적용내용]==========
적용될 기존 열차 이름 : `Luggage_Car`

**Comment by CoconutKR** [comment]
Very Good
