### ISSUE TITLE
[열차변경] GTA-A 수정 / 회사 색상(2nd company 정상 적용 확인 필요)

### ISSUE THREAD

**Issue by JukjeonWani** [OpenCreative/KR_Plus_Set#67]
==========[필수스프라이트]==========
* 현존도색(팬터그래프 추가)
![GTX-A_original](https://user-images.githubusercontent.com/88026704/218968798-8645d322-8ecf-4bdf-a78d-eea67ec5964f.png)
ref. https://youtu.be/f1TCsEgLyoc

* 회사 색상(2nd company 색상 있음)
![GTX-A_company](https://user-images.githubusercontent.com/88026704/218968860-cc43a8e7-ade3-492c-a801-79b73cb7805f.png)
**부분적으로 ***2nd company*** 색상이 사용되었습니다.**

==========[설명]==========
GTX 차량에 팬터그래프 추가 및 회사 색상 스프라이트 추가

==========[KTS+적용내용]==========
적용될 기존 열차 이름: GTX
도색 추가시 열차 이름: 기본 도색, 회사 색상

**Comment by evepoi** [comment]
코딩결과 : 회사색상 전체적으로 바뀌며, 두번째 색상으로는 변경되지 않습니다.

한국열차세트와 차별화 두기 위해 회사색상으로 변경해두는 것도 좋은 선택으로 보여지며, 수정전까지 코딩된 사항을 그대로 유지하는 것으로 하겠습니다.

**Comment by JukjeonWani** [comment]
> 코딩결과 : 회사색상 전체적으로 바뀌며, 두번째 색상으로는 변경되지 않습니다.
> 
> 한국열차세트와 차별화 두기 위해 회사색상으로 변경해두는 것도 좋은 선택으로 보여지며, 수정전까지 코딩된 사항을 그대로 유지하는 것으로 하겠습니다.

팔레트 및 해석표 확인 결과 색상이 잘못 들어가진 않은 것 같습니다. 테스트버전 올라가면 확인해보겠습니다.
